### ISSUE TITLE
tiny build docs error

### ISSUE THREAD

**Issue by datgame** [thennequin/Texeled#6]
change build instruction from "scripts\build.bat vs2017" to "cd scripts && build.bat vs2017"
or it won't find genie.exe downloaded to the scripts-folder.
or add a 
pushd %~dp0
to the top of your .bat-file
and popd at the end

**Comment by thennequin** [comment]
Indeed I forgot the ``%~dp0`` somewhere.
I fix the scripts in revision 2d0c71f410b8804aca3092f53976513853c39064.
Now you can do both.
